version: '2'
services:
  web:
    build: ./NSpM-service
    command: node index.js
    volumes:
      - ./NSpM-service:/usr/app/
      - ../NSpM:/usr/NSpM/
      - /usr/app/node_modules
    ports:
      - "5000:5000"
